=== hohoangkha16092002/XML/phieuDiem.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="PhieuDiem">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="HocSinh">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="HoTen">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="5"/>
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Lop">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:length value="4"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="DiaChi" type="xs:string"/>
                            <xs:element name="GioiTinh">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Nam"/>
                                        <xs:enumeration value="Ná»¯"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="NgaySinh" type="xs:date"/>
                        </xs:sequence>
                        <xs:attribute name="maHS" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="[0-9]{5}"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="BangDiem">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="MonHoc">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="STT">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:unsignedByte">
                                                  <xs:minExclusive value="0"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="TenMon">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:minLength value="5"/>
                                                  <xs:maxLength value="50"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="DiemHK1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:float">
                                                  <xs:minInclusive value="0"/>
                                                  <xs:maxInclusive value="10"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="DiemHK2">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:float">
                                                  <xs:minInclusive value="0"/>
                                                  <xs:maxInclusive value="10"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                    <xs:key name="MaMH_Key">
                        <xs:selector xpath="MonHoc"/>
                        <xs:field xpath="STT"/>
                    </xs:key>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== hohoangkha16092002/XML/phieuDiem.xml
<?xml version="1.0" encoding="UTF-8"?>
<PhieuDiem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="phieudiem.xsd">
    <HocSinh maHS="12345">
        <HoTen>Ho Hoang Kha</HoTen>
        <Lop>10A6</Lop>
        <DiaChi>Tuy Hoa</DiaChi>
        <GioiTinh>Nam</GioiTinh>
        <NgaySinh>2002-09-16</NgaySinh>
    </HocSinh>
    <BangDiem>
        <MonHoc>
            <STT>1</STT>
            <TenMon>TBHK1</TenMon>
            <DiemHK1>10</DiemHK1>
            <DiemHK2>10</DiemHK2>
        </MonHoc>
        
        <MonHoc>
            <STT>2</STT>
            <TenMon>TBHK1</TenMon>
            <DiemHK1>9</DiemHK1>
            <DiemHK2>9</DiemHK2>
        </MonHoc>

        <MonHoc>
            <STT>32</STT>
            <TenMon>TBHK1</TenMon>
            <DiemHK1>10</DiemHK1>
            <DiemHK2>9</DiemHK2>
        </MonHoc>
        
        <MonHoc>
            <STT>3</STT>
            <TenMon>TBHK1</TenMon>
            <DiemHK1>8</DiemHK1>
            <DiemHK2>8</DiemHK2>
        </MonHoc>
        
        <MonHoc>
            <STT>4</STT>
            <TenMon>CCTC1</TenMon>
            <DiemHK1>10</DiemHK1>
            <DiemHK2>9</DiemHK2>
        </MonHoc>
    </BangDiem>
</PhieuDiem>
