=== hohoangkha16092002/XML/student.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT student (firstName,lastName,id,plan,note) >
<!ELEMENT firstName (#PCDATA) >
<!ELEMENT lastName (#PCDATA) >
<!ELEMENT id (#PCDATA) >
<!ELEMENT plan (courses)+>
<!ELEMENT courses (course)+>
<!ATTLIST courses year CDATA "1" >
<!ELEMENT course (name,shortName,record?) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT shortName (#PCDATA) >
<!ELEMENT record (grade,date) >
<!ELEMENT grade (#PCDATA) >
<!ELEMENT date (#PCDATA) >
<!ELEMENT note (#PCDATA|department)* >
<!ELEMENT department (#PCDATA) >

=== hohoangkha16092002/XML/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE student SYSTEM "student.dtd">
<student>
    <firstName>Ka</firstName>
    <lastName>Ho</lastName>
    <id>123</id>
    <plan>
        <courses year="2">
            <course>
                <name>C++</name>
                <shortName>CPL</shortName>
                <record>
                    <grade>30</grade>
                    <date>13/03/2020</date>
                </record>
            </course>
            <course>
                <name>Software Engineering</name>
                <shortName>SE</shortName>
            </course>
        </courses>
    </plan>
    <note>Please contact <department>Information Technology</department> to get details.</note>
</student>
