=== hohoangkha16092002/XML/thuVien.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT thuVien (sach+)>
<!ELEMENT sach (id,ten,tacGia,(nhaXuatBan,gia)+)>
<!ELEMENT id (#PCDATA) >
<!ELEMENT ten (#PCDATA) >
<!ELEMENT tacGia (#PCDATA) >
<!ELEMENT nhaXuatBan (#PCDATA) >
<!ELEMENT gia (#PCDATA) >
<!ATTLIST sach ngonNgu CDATA #IMPLIED 
                theLoai (KhoaHoc|GiaiTri|TinHoc) #REQUIRED>
<!ENTITY NXBT "Nhà Xuất Bản Trẻ" >
<!ENTITY NXBGD "Nhà Xuất Bản Giáo Dục" >

=== hohoangkha16092002/XML/thuVien.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE thuVien SYSTEM "thuVien.dtd">
<thuVien xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="thuVien.xsd">
    <sach theLoai="GiaiTri">
        <id>001</id>
        <ten>Mắt Biếc</ten>
        <tacGia>Nguyễn Nhật Ánh</tacGia>
        <nhaXuatBan>&NXBT;</nhaXuatBan>
        <gia>100000</gia>
    </sach>
    <sach theLoai="TinHoc">
        <id>002</id>
        <ten>Công nghệ XML và ứng dụng</ten>
        <tacGia>Phan Thị Thu Thủy</tacGia>
        <nhaXuatBan>&NXBGD;</nhaXuatBan>
        <gia>100000</gia>
    </sach>
</thuVien>
