=== hohoangkha16092002/XML/GIUAKY/1.dtd
<!ELEMENT session (date, chude, nhom+)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT chude (#PCDATA)>
<!ELEMENT nhom (quanly, siso, ds_thamdu)>
<!ATTLIST nhom name CDATA #REQUIRED>
<!ELEMENT quanly (#PCDATA)>
<!ELEMENT siso (#PCDATA)>
<!ELEMENT ds_thamdu (sv+)>
<!ELEMENT sv (#PCDATA)>
<!ATTLIST sv status CDATA #REQUIRED>

=== hohoangkha16092002/XML/GIUAKY/1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE session SYSTEM "1.dtd">
<session>
    <date>20/09/2023</date>
    <chude>Họp tổ chức Fes</chude>
    <nhom name="ABC">
        <quanly>Tiến</quanly>
        <siso></siso>
        <ds_thamdu>
            <sv status="NhomTruong">A</sv>
            <sv status="NhomPho">B</sv>
            <sv status="ThuKy">C</sv>
        </ds_thamdu>
    </nhom>
    <nhom name="DEF">
        <quanly>Kha</quanly>
        <siso></siso>
        <ds_thamdu>
            <sv status="NhomTruong">D</sv>
            <sv status="ThuKy">E</sv>
        </ds_thamdu>
    </nhom>
</session>
