=== hohoangkha16092002/XML/Schema/diemDanh.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="mssvType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{8}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TenLopType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{2}[.][A-Z]{4}"/>
            <xs:length value="7"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="NamType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{4}"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:element name="DiemDanh">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="Lop">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="TenLop" type="TenLopType"/>
                            <xs:element name="ThoiGian">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Thang">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:byte">
                                                  <xs:minInclusive value="1"/>
                                                  <xs:maxInclusive value="12"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Nam" type="NamType"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element maxOccurs="unbounded" name="SinhVien">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="MSSV" type="mssvType"/>
                                        <xs:element name="HoTen" type="xs:string"/>
                                        <xs:element name="SoLanVang">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:byte">
                                                  <xs:minExclusive value="0"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="LyDoVang" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== hohoangkha16092002/XML/Schema/diemDanh.xml
<?xml version="1.0" encoding="UTF-8"?>
<DiemDanh xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/D:/LEARN/XML/diemdanh.xsd">
    <Lop>
        <TenLop>00.AAAA</TenLop>
        <ThoiGian>
            <Thang>6</Thang>
            <Nam>0000</Nam>
        </ThoiGian>
        <SinhVien>
            <MSSV>00000000</MSSV>
            <HoTen>HoTen0</HoTen>
            <SoLanVang>64</SoLanVang>
            <LyDoVang>LyDoVang0</LyDoVang>
        </SinhVien>
        <SinhVien>
            <MSSV>00000000</MSSV>
            <HoTen>HoTen1</HoTen>
            <SoLanVang>64</SoLanVang>
            <LyDoVang>LyDoVang1</LyDoVang>
        </SinhVien>
    </Lop>
    <Lop>
        <TenLop>00.AAAA</TenLop>
        <ThoiGian>
            <Thang>6</Thang>
            <Nam>0000</Nam>
        </ThoiGian>
        <SinhVien>
            <MSSV>00000000</MSSV>
            <HoTen>HoTen2</HoTen>
            <SoLanVang>64</SoLanVang>
            <LyDoVang>LyDoVang2</LyDoVang>
        </SinhVien>
        <SinhVien>
            <MSSV>00000000</MSSV>
            <HoTen>HoTen3</HoTen>
            <SoLanVang>64</SoLanVang>
            <LyDoVang>LyDoVang3</LyDoVang>
        </SinhVien>
    </Lop>
</DiemDanh>
