=== hohoangkha16092002/XML/Schema/maTran.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="MATRAN">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="DONG">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element form="qualified" maxOccurs="unbounded" name="COT"
                                nillable="false"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute form="unqualified" name="dong" type="xs:int" use="optional"/>
            <xs:attribute name="cot" type="xs:int"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== hohoangkha16092002/XML/XSLT/bai_4_maTran.xml
<?xml version="1.0" encoding="UTF-8"?>
<MATRAN xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="matran.xsd" dong="4" cot="3">
    <DONG>
        <COT>1</COT>
        <COT>4</COT>
        <COT>12</COT>
    </DONG>
    <DONG>
        <COT>-23</COT>
        <COT>7</COT>
        <COT>50</COT>
    </DONG>
    <DONG>
        <COT>4</COT>
        <COT>0</COT>
        <COT>25</COT>    
    </DONG>
    <DONG>
        <COT>14</COT>
        <COT>35</COT>
        <COT>-5</COT>    
    </DONG>
</MATRAN>
