=== hohoangkha16092002/XML/XSLT/bai_7_KetQua.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="DSKQ">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="KetQua">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaSinhVien" type="xs:string"/>
                            <xs:element name="MaMonHoc" type="xs:string"/>
                            <xs:element name="DiemThi">
                                <xs:simpleType>
                                    <xs:restriction base="xs:short">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== hohoangkha16092002/XML/XSLT/bai_7_KetQua.xml
<?xml version="1.0" encoding="UTF-8"?>
<DSKQ xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/D:/LEARN/XML/XSLT/bai_7_KetQua.xsd">
    <KetQua>
        <MaSinhVien>MaSinhVien0</MaSinhVien>
        <MaMonHoc>MaMonHoc0</MaMonHoc>
        <DiemThi>3</DiemThi>
    </KetQua>
    <KetQua>
        <MaSinhVien>MaSinhVien1</MaSinhVien>
        <MaMonHoc>MaMonHoc1</MaMonHoc>
        <DiemThi>5</DiemThi>
    </KetQua>
    <KetQua>
        <MaSinhVien>MaSinhVien3</MaSinhVien>
        <MaMonHoc>MaMonHoc1</MaMonHoc>
        <DiemThi>10</DiemThi>
    </KetQua>
</DSKQ>
