=== hohoangkha16092002/XML/XSLT/bai_7_monhoc.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="DSMH">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="MonHoc">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaMonHoc" type="xs:string"/>
                            <xs:element name="TenMonHoc" type="xs:string"/>
                            <xs:element name="SoGio">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="4"/>
                                        <xs:maxInclusive value="48"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="Key_MaMonHoc">
            <xs:selector xpath="MonHoc"/>
            <xs:field xpath="MaMonHoc"/>
        </xs:key>
    </xs:element>
</xs:schema>

=== hohoangkha16092002/XML/XSLT/bai_7_monhoc.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="bai_7_monhoc.xsl"?>
<DSMH xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/D:/LEARN/XML/XSLT/bai_7_monhoc.xsd">
    <MonHoc>
        <MaMonHoc>CSDL</MaMonHoc>
        <TenMonHoc>Cơ sở dữ liệu</TenMonHoc>
        <SoGio>30</SoGio>
    </MonHoc>
    <MonHoc>
        <MaMonHoc>MCB</MaMonHoc>
        <TenMonHoc>Mạng căn bản</TenMonHoc>
        <SoGio>30</SoGio>
    </MonHoc>
    <MonHoc>
        <MaMonHoc>THDC</MaMonHoc>
        <TenMonHoc>Tin học đại cương</TenMonHoc>
        <SoGio>45</SoGio>
    </MonHoc>
    <MonHoc>
        <MaMonHoc>THVP</MaMonHoc>
        <TenMonHoc>Tin học văn phòng</TenMonHoc>
        <SoGio>45</SoGio>
    </MonHoc>
    <MonHoc>
        <MaMonHoc>XLA</MaMonHoc>
        <TenMonHoc>Xử lý ảnh</TenMonHoc>
        <SoGio>45</SoGio>
    </MonHoc>
</DSMH>
