=== hohoangkha16092002/XML/XSLT/bai_6_sinhvien.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="DSSV">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="SinhVien">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="TenSV" type="xs:string"/>
                            <xs:element name="GioiTinh">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Nam"/>
                                        <xs:enumeration value="Ná»¯"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="NgaySinh" type="xs:date"/>
                            <xs:element name="MaLop">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z]{4}[0-9]{2}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="mssv">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:length value="8"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== hohoangkha16092002/XML/XSLT/bai_6_sinhvien.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="bai_6_sinhvien.xsl"?>
<DSSV xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="bai_6_sinhvien.xsd">
    <SinhVien mssv ="62130808">
        <TenSV>Hồ Hoàng Kha</TenSV> 
        <GioiTinh>Nam</GioiTinh>
        <NgaySinh>2002-09-16</NgaySinh>
        <MaLop>CNTT01</MaLop>
    </SinhVien> 
    <SinhVien mssv ="62130823">
        <TenSV>Hồ Đắc Tài</TenSV> 
        <GioiTinh>Nam</GioiTinh>
        <NgaySinh>1985-01-02</NgaySinh>
        <MaLop>CTHH02</MaLop>
    </SinhVien>
    <SinhVien mssv ="61148304">
        <TenSV>Bùi Thị Tú Nhi</TenSV> 
        <GioiTinh>Nữ</GioiTinh>
        <NgaySinh>1992-01-12</NgaySinh>
        <MaLop>GVCN21</MaLop>
    </SinhVien>
</DSSV>
