=== hohoangkha16092002/XML/SQL/sinhvien.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="root">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="row" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="STT">
                                <xs:annotation>
                                    <xs:documentation>
                                        The "INT" type from the data base was mapped to "xs:integer" XML Schema type.
                                    </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:maxInclusive value="2147483647"/>
                                        <xs:minInclusive value="-2147483648"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Name">
                                <xs:annotation>
                                    <xs:documentation>
                                        The "VARCHAR" type from the data base was mapped to "xs:string" XML Schema type.
                                    </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Class">
                                <xs:annotation>
                                    <xs:documentation>
                                        The "TINYTEXT" type from the data base was mapped to "xs:string" XML Schema type.
                                    </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="255"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== hohoangkha16092002/XML/SQL/sinhvien.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="file:/D:/LEARN/XML/SQL/sinhvien.xsd">
    <row>
        <STT>1</STT>
        <Name>Hoang Kha</Name>
        <Class>CNTT3</Class>
    </row>
    <row>
        <STT>2</STT>
        <Name>Minh Ti?n</Name>
        <Class>CNTT3</Class>
    </row>
</root>
